title: izebit | Blog about programming
author: Artem Konovalov
email: izebit@gmail.com
url: https://izebit.ru
baseurl: "/"
description: >
  This website is a personal blog. Mainly there are articles about
  java programming, but you can find ones on other topics.

permalink: /:slug.html

favicon: "icon.png" # name+extension of favicon (which must be put on the root folder)

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

kramdown:
  hard_wrap: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - "*.iml"